export const CALENDER_LIST_REQUEST = " CALENDER_LIST_REQUEST";
export const CALENDER_LIST_SUCCESS = " CALENDER_LIST_SUCCESS";
export const CALENDER_LIST_FAIL = "    CALENDER_LIST_FAIL";

export const CALENDER_DETAILS_REQUEST = "CALENDER_DETAILS_REQUEST";
export const CALENDER_DETAILS_SUCCESS = "CALENDER_DETAILS_SUCCESS";
export const CALENDER_DETAILS_FAIL = "CALENDER_DETAILS_FAIL";

export const CALENDER_CREATE_REQUEST = "CALENDER_CREATE_REQUEST";
export const CALENDER_CREATE_SUCCESS = "CALENDER_CREATE_SUCCESS";
export const CALENDER_CREATE_FAIL = "CALENDER_CREATE_FAIL";
export const CALENDER_CREATE_RESET = "CALENDER_CREATE_RESET";

export const CALENDER_UPDATE_REQUEST = "CALENDER_UPDATE_REQUEST";
export const CALENDER_UPDATE_SUCCESS = "CALENDER_UPDATE_SUCCESS";
export const CALENDER_UPDATE_FAIL = "CALENDER_UPDATE_FAIL";
export const CALENDER_UPDATE_RESET = "CALENDER_UPDATE_RESET";

export const CALENDER_DELETE_REQUEST = "CALENDER_DELETE_REQUEST";
export const CALENDER_DELETE_SUCCESS = "CALENDER_DELETE_SUCCESS";
export const CALENDER_DELETE_FAIL = "CALENDER_DELETE_FAIL";
export const CALENDER_DELETE_RESET = "CALENDER_DELETE_RESET";
