export const INSTANCE_LIST_REQUEST = " INSTANCE_LIST_REQUEST";
export const INSTANCE_LIST_SUCCESS = " INSTANCE_LIST_SUCCESS";
export const INSTANCE_LIST_FAIL = "    INSTANCE_LIST_FAIL";

export const INSTANCE_DETAILS_REQUEST = "INSTANCE_DETAILS_REQUEST";
export const INSTANCE_DETAILS_SUCCESS = "INSTANCE_DETAILS_SUCCESS";
export const INSTANCE_DETAILS_FAIL = "INSTANCE_DETAILS_FAIL";

export const INSTANCE_CREATE_REQUEST = "INSTANCE_CREATE_REQUEST";
export const INSTANCE_CREATE_SUCCESS = "INSTANCE_CREATE_SUCCESS";
export const INSTANCE_CREATE_FAIL = "INSTANCE_CREATE_FAIL";
export const INSTANCE_CREATE_RESET = "INSTANCE_CREATE_RESET";

export const INSTANCE_UPDATE_REQUEST = "INSTANCE_UPDATE_REQUEST";
export const INSTANCE_UPDATE_SUCCESS = "INSTANCE_UPDATE_SUCCESS";
export const INSTANCE_UPDATE_FAIL = "INSTANCE_UPDATE_FAIL";
export const INSTANCE_UPDATE_RESET = "INSTANCE_UPDATE_RESET";

export const INSTANCE_DELETE_REQUEST = "INSTANCE_DELETE_REQUEST";
export const INSTANCE_DELETE_SUCCESS = "INSTANCE_DELETE_SUCCESS";
export const INSTANCE_DELETE_FAIL = "INSTANCE_DELETE_FAIL";
export const INSTANCE_DELETE_RESET = "INSTANCE_DELETE_RESET";
