export const ITEMSTATUS_LIST_REQUEST = " ITEMSTATUS_LIST_REQUEST";
export const ITEMSTATUS_LIST_SUCCESS = " ITEMSTATUS_LIST_SUCCESS";
export const ITEMSTATUS_LIST_FAIL = "    ITEMSTATUS_LIST_FAIL";

export const ITEMSTATUS_DETAILS_REQUEST = "ITEMSTATUS_DETAILS_REQUEST";
export const ITEMSTATUS_DETAILS_SUCCESS = "ITEMSTATUS_DETAILS_SUCCESS";
export const ITEMSTATUS_DETAILS_FAIL = "ITEMSTATUS_DETAILS_FAIL";

export const ITEMSTATUS_CREATE_REQUEST = "ITEMSTATUS_CREATE_REQUEST";
export const ITEMSTATUS_CREATE_SUCCESS = "ITEMSTATUS_CREATE_SUCCESS";
export const ITEMSTATUS_CREATE_FAIL = "ITEMSTATUS_CREATE_FAIL";
export const ITEMSTATUS_CREATE_RESET = "ITEMSTATUS_CREATE_RESET";

export const ITEMSTATUS_UPDATE_REQUEST = "ITEMSTATUS_UPDATE_REQUEST";
export const ITEMSTATUS_UPDATE_SUCCESS = "ITEMSTATUS_UPDATE_SUCCESS";
export const ITEMSTATUS_UPDATE_FAIL = "ITEMSTATUS_UPDATE_FAIL";
export const ITEMSTATUS_UPDATE_RESET = "ITEMSTATUS_UPDATE_RESET";

export const ITEMSTATUS_DELETE_REQUEST = "ITEMSTATUS_DELETE_REQUEST";
export const ITEMSTATUS_DELETE_SUCCESS = "ITEMSTATUS_DELETE_SUCCESS";
export const ITEMSTATUS_DELETE_FAIL = "ITEMSTATUS_DELETE_FAIL";
export const ITEMSTATUS_DELETE_RESET = "ITEMSTATUS_DELETE_RESET";
